// Blog Approval API
// Handles post approval and publication

const posts = [
  {
    id: 1,
    title: "AI Tools Roundup: April 2026",
    slug: "ai-tools-roundup-april-2026",
    author: "Vesper",
    category: "Research",
    status: "pending",
    wordCount: 800,
    createdAt: "2026-04-06T00:00:00Z"
  },
  {
    id: 2,
    title: "Email Templates Deep Dive",
    slug: "email-templates-deep-dive",
    author: "Lena",
    category: "Email",
    status: "pending",
    wordCount: 1200,
    createdAt: "2026-04-06T00:00:00Z"
  },
  {
    id: 3,
    title: "Productivity Framework 2026",
    slug: "productivity-framework-2026",
    author: "Mace",
    category: "Productivity",
    status: "approved",
    wordCount: 950,
    createdAt: "2026-04-05T00:00:00Z",
    approvedAt: "2026-04-05T22:00:00Z"
  }
];

// Approve a post
export async function approvePost(postId) {
  const post = posts.find(p => p.id === postId);
  if (!post) {
    return { error: "Post not found" };
  }
  
  post.status = "approved";
  post.approvedAt = new Date().toISOString();
  
  // Generate blog file
  await generateBlogFile(post);
  
  return { 
    success: true, 
    message: "Post approved and ready to publish",
    post 
  };
}

// Publish a post (go live)
export async function publishPost(postId) {
  const post = posts.find(p => p.id === postId);
  if (!post) {
    return { error: "Post not found" };
  }
  
  if (post.status !== "approved") {
    return { error: "Post must be approved first" };
  }
  
  post.status = "published";
  post.publishedAt = new Date().toISOString();
  
  // Trigger deployment
  await triggerDeployment();
  
  return {
    success: true,
    message: "Post published successfully",
    url: `https://thezeromethod.com/blog/${post.slug}`,
    post
  };
}

// Generate blog file for website
async function generateBlogFile(post) {
  // In real implementation, this would write to the website repo
  const template = `
---
export async function getStaticPaths() {
  return [{ params: { slug: '${post.slug}' } }];
}

const post = {
  title: "${post.title}",
  author: "${post.author}",
  date: "${new Date().toLocaleDateString()}",
  category: "${post.category}"
};
---

<!-- Auto-generated blog post -->
<div style="text-align: center; max-width: 700px; margin: 0 auto;">
  <h1>${post.title}</h1>
  <!-- Content generated by ${post.author} -->
</div>
  `;
  
  console.log(`Generated blog file for: ${post.slug}`);
  return template;
}

// Trigger Vercel deployment
async function triggerDeployment() {
  // In production, this would call Vercel API
  console.log("Triggering deployment...");
  return true;
}

// Get all posts
export function getPosts() {
  return posts;
}

// Get posts by status
export function getPostsByStatus(status) {
  return posts.filter(p => p.status === status);
}